### ISSUE TITLE
country code

### ISSUE THREAD

**Issue by Tonyabdelsater** [TheSpeedX/TBomb#101]
The lebanese country code (961)is missing could you add it please.
It would be like this.::      961:LB

**Comment by 0n1cOn3** [comment]
Thank you fo your feedback.

We have at the moment no API's for Lebanese. If you are a developer, we would be very appreciated when you can provide us some API's for your location. 

Sincerly

0n1cOn3

**Comment by TheSpeedX** [comment]
@Tonyabdelsater  its there in list
