### ISSUE TITLE
Improper way of checking active internet connection

### ISSUE THREAD

**Issue by t0xic0der** [TheSpeedX/TBomb#110]
The exception handling routine put to use for checking active internet connection is broad so it can catch other exceptions as well - those which might not even be the absence of internet connection. Please be specific about the caught exception.

**Comment by t0xic0der** [comment]
Also for the record, sites like `www.google.com` might not be available in countries like China, it is suggested to rather check reachability to GitHub (or maybe to this repository also :wink:)

**Comment by 0n1cOn3** [comment]
Gonna change that asap. SpeedX will add the PR after pinging him in Whatsapp.

**Comment by t0xic0der** [comment]
Cool. Anyhow I was working on this issue on my fork . Might make a PR very soon. :slightly_smiling_face:

**Comment by 0n1cOn3** [comment]
Alright, then im waiting for your PR instead 👍

**Comment by TheSpeedX** [comment]
This issue has been fixed. Reopen this if issue still persist.
