### ISSUE TITLE
Mobile number hardcoded in AJIO's request

### ISSUE THREAD

**Issue by t0xic0der** [TheSpeedX/TBomb#115]
I do not know if it is an expected change but the mobile number in the AJIO's request is hardcoded. You are requested to look into it.

**Comment by TheSpeedX** [comment]
@t0xic0der Thanks a lot for putting much time into reviewing the code
I have quite a few updates to make as well as some new features but due to some issues i wasnt able to work on it

I will surely try to work on it this week and try to make code more readable

**Comment by t0xic0der** [comment]
You're welcome @TheSpeedX and thanks for making this project open-source. I have been working on rewriting the code lately in a branch of my fork to optimize and speed up operations by almost 75%. It is a work-in-progress but feel free to [take a look](https://github.com/t0xic0der/TBomb/tree/refactoring-improvements).

I will make a PR when it is ready. :slightly_smiling_face:

**Comment by TheSpeedX** [comment]
This issue has been fixed
