### ISSUE TITLE
Landline support 

### ISSUE THREAD

**Issue by dstar22** [TheSpeedX/TBomb#118]
I want to call bomber a landline number could you add support for it as it uses 022 in india without plus sign

**Comment by t0xic0der** [comment]
The APIs present herewith are mostly based on sending OTPs and confirmations to the clients. A landline is not a device where you would want to receive OTPs so much naturally, bombing it with those messages can be tricky. What do you say @0n1cOn3?

**Comment by dstar22** [comment]
ohh that's sad

**Comment by 0n1cOn3** [comment]
Im Agree @t0xic0der
