### ISSUE TITLE
Error while executing -requirements

### ISSUE THREAD

**Issue by krishnahemanth** [TheSpeedX/TBomb#121]
![Screenshot_20200704-020230](https://user-images.githubusercontent.com/47827892/86496343-a5a6b280-bd9a-11ea-83cd-b8b18575ce6e.png)

**Comment by 0n1cOn3** [comment]
Upgrade your pip

pip install --upgrade pip

**Comment by krishnahemanth** [comment]
Hey , ran that command, the same error shiws up, using termux btw.

**Comment by t0xic0der** [comment]
> Hey , ran that command, the same error shows up, using termux btw.

Hi @krishnahemanth. can you confirm the presence of active internet connection on your phone? The errors show in the screenshot pretty much indicate otherwise.

**Comment by jaym20** [comment]
You need openssl.
Install it by running pkg install openssl
