### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by Kingrui380** [TheSpeedX/TBomb#123]
![IMG_0427](https://user-images.githubusercontent.com/68143780/87393392-b0eeaf00-c5e0-11ea-8f7d-808b3504248b.png)
🌚

**Comment by Kingrui380** [comment]
![IMG_0428](https://user-images.githubusercontent.com/68143780/87393797-4722d500-c5e1-11ea-8ffd-42f8945aff5c.png)

**Comment by 0n1cOn3** [comment]
Your looking with an iPad App. The Code has been writen for PC & Termux User. :) 

That could be the reason why the logo will be shown as fault.

**Comment by t0xic0der** [comment]
Also, @0n1cOn3 - The user is expected to execute the script in iPad/iPhone/Android etc. They are not expected to develop on the code on such platforms when they can do so easily on a PC.

**Comment by 0n1cOn3** [comment]
TBomb was offical not released for macOS nor Windows. 

Nowadays, we've extendet the support. And Pythonista for iOS is a full fledge IDE, yeah. But thats not supported in this case with TBomb. Aswell iOS is not supported.

**Comment by AvinashReddy3108** [comment]
> ![IMG_0428](https://user-images.githubusercontent.com/68143780/87393797-4722d500-c5e1-11ea-8ffd-42f8945aff5c.png)

Try doing this on a VPN.
I guess GitHub (.com) might not be open to China.

**Comment by 0n1cOn3** [comment]
Please change for your purpose github against this adress and try again:

https://www.jpl.nasa.gov/

Now:
> def checkinternet():
    res = False
    try:
        # requests.get('https://github.com/', verify=True)
        requests.get('https://github.com/')
        res = False

> def checkinternet():
    res = False
    try:
        # requests.get('https://www.jpl.nasa.gov/', verify=True)
        requests.get('https://www.jpl.nasa.gov/')
        res = False

Please let us know, if this has fixed your issue!

Sincerly

0n1cOn3

**Comment by TheSpeedX** [comment]
Kindly update to latest version and reopen the issue if it still happens
