### ISSUE TITLE
Help plz

### ISSUE THREAD

**Issue by z0ng-X** [TheSpeedX/TBomb#132]
"[!] Error: some dependencies are not installed
Type 'pip install -r requirements.txt' to install all required packages"

i write "pip install -r requirements"
and they write to me this "DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2- support

Requirement already satisfied: requests <3,> = 2 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2.23.0 )
Requirement already satisfied: urllib3 <2,> = 1 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (1.25.10 )
Requirement already satisfied: certifi> = 2017.4.17 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from requests <3,> = 2 -> - r requirements.txt ( line 1)) (2020.6.20)
Requirement already satisfied: chardet <4,> = 3.0.2 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from requests <3,> = 2 -> - r requirements .txt (line 1)) (3.0.4)
Requirement already satisfied: idna <3,> = 2.5 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from requests <3,> = 2 -> - r requirements.txt (line 1)) (2.10)"
help me please

**Comment by dedshit** [comment]
use pip3

its not python2 😬😬

**Comment by TheSpeedX** [comment]
@z0ng-X 
try pip3 install -r requirements.txt instead

Make sure your requirements are installed in python v3
