### ISSUE TITLE
Sms cant recive

### ISSUE THREAD

**Issue by SOP1I69M** [TheSpeedX/TBomb#134]
I tried it on my phone .....sometimes it says it succeful request but i get nothing and some times it stops and doesnt work....... like it freez

**Comment by TheSpeedX** [comment]
Kindly update to latest version

**Comment by SOP1I69M** [comment]
How i can update pls tell me

في الجمعة، ٣١ يوليو، ٢٠٢٠ ٢:٠١ م SpeedX <notifications@github.com> كتب:

**Comment by 0n1cOn3** [comment]
Due misusing of TBomb, several API's died. Don't be afraid if you don't see all send messages.

Option 3 in TBomb - Update TBomb

**Comment by TheSpeedX** [comment]
Issue closed due to inactivity.
