### ISSUE TITLE
Additional String required for iSH

### ISSUE THREAD

**Issue by 0n1cOn3** [TheSpeedX/TBomb#138]
There two missing strings while installing all requirements:

Python3-Pip is under iSH: py3-pip
toilet is aswell missing like for macOS under iSH

**Comment by TheSpeedX** [comment]
toilet is not a necessary dependency.
The script will write text normally if toilet was not found

As of pip for for python3 it gets installed along with python3, when you run `apk add python3` as per docs

Can you verify that?

**Comment by 0n1cOn3** [comment]
Not on iSH. You have to install Pip manually😕

**Comment by scpketer** [comment]
It'll be a lot better to make TBomb a PyPI package (so it can be installed with pip)

**Comment by TheSpeedX** [comment]
Yeah, Yeah that be done soon enough with reference to Issue #109

**Comment by 0n1cOn3** [comment]
> It'll be a lot better to make TBomb a PyPI package (so it can be installed with pip)

There's just one issue...
The package for iSH (alpine on iOS) does not include missing package eighter due the fact, that it is just a x86 emulated alpine and not an x86-64. The x86 repo is kinda cribbed...
