### ISSUE TITLE
Geting error 

### ISSUE THREAD

**Issue by Djshacker** [TheSpeedX/TBomb#140]
Getting error in new update.... 
Cant run the tool

**Comment by klSilent** [comment]
Me too :(

![image](https://user-images.githubusercontent.com/30533265/89066929-fba94e80-d376-11ea-9203-0e909c50e8c1.png)

**Comment by klSilent** [comment]
Me too :(

![image](https://user-images.githubusercontent.com/30533265/89066947-04018980-d377-11ea-9fa2-b524463a01e6.png)

**Comment by klSilent** [comment]
Me too :(

![tbomb](https://user-images.githubusercontent.com/30533265/89066979-15e32c80-d377-11ea-8da7-bd35b3db33db.PNG)

**Comment by klSilent** [comment]
![tbomb](https://user-images.githubusercontent.com/30533265/89070187-4201ac00-d37d-11ea-8fef-b1d0701280df.PNG)

**Comment by 0n1cOn3** [comment]
@t0xic0der @TheSpeedX

**Comment by TheSpeedX** [comment]
Can you test now just run 
`python3 bomber.py --update ` or from `TBomb.sh`

**Comment by klSilent** [comment]
![image](https://user-images.githubusercontent.com/30533265/89076393-db828b00-d388-11ea-99ae-12870e9866e6.png)

**Comment by klSilent** [comment]
Unfortunately it doesn't work. I updated it, I installed TBomb again but now it just looks like this:

[ ✔ ] Version: v2.0b

[ # ] Contributors: SpeedX t0xic0der scpketer Stefan

[ # ] Checking for updates
[ ! ] An update is available
      Starting update...
UPDATING .

[ ✔ ] TBomb was updated to the latest version
      Please run the script again to load the latest version
root@kali:~/TBomb#

**Comment by klSilent** [comment]
@TheSpeedX @t0xic0der

**Comment by klSilent** [comment]
That's it, now it works!

**Comment by klSilent** [comment]
Now I'm going to add the phone number but unfortunately I don't receive any message

**Comment by 0n1cOn3** [comment]
@klSilent 

Any issues about API or missing msg's goes to @TheSpeedX

**Comment by TheSpeedX** [comment]
@klSilent  Which Country?

**Comment by vicky0852** [comment]
@TheSpeedX  
 After adding the phone number but I don't receive any message and calls, am from India

**Comment by TheSpeedX** [comment]
TBomb was reverted to old version till fixes apply to the new one

**Comment by pepemalo** [comment]
@TheSpeedX I don't get the messages I have Version: 2.1.2
