### ISSUE TITLE
SMS bombing not working after update

### ISSUE THREAD

**Issue by lavish440** [TheSpeedX/TBomb#145]
The script says it sent 10 SMS but the victim receives only 1 or 2.

**Comment by 0n1cOn3** [comment]
Due misusing of TBomb, several API's died. Don't be afraid if you don't see all send messages.

**Comment by lavish440** [comment]
Most of the times no message is sent. Everything worked fine with version 2.0. This only started happening after the devs downgraded the tool.

**Comment by 0n1cOn3** [comment]
You can say @scpketer @darkestentropy thank you. Before the bomber.py has been deobfuscated, all API's worked like a charm. SpeedX toöd more then once, bomber.py due misuse not to decrypt. Bot those twi guys forced him for that and there we are today. After a year, TBomb is almost dead...

**Comment by scpketer** [comment]
*just as planned*, @0n1cOn3 :P

**Comment by 0n1cOn3** [comment]
You know what i mean ;-)

**Comment by scpketer** [comment]
Nope, I don't think so.

**Comment by 0n1cOn3** [comment]
TBomb was never injected with a bad code. Kist decrypted due the misuse of the APIs. Now we have the salat 😅

**Comment by scpketer** [comment]
I never stated the otherwise, pal.

**Comment by 0n1cOn3** [comment]
> I never stated the otherwise, pal.
> 
> Besides, API endpoints are _extremely_ subject to change, so don't blame it on us.

Well, SpeedX explained why bomber.py was encrypted...

And you did kinda someting like that ;-)
See  #19

**Comment by scpketer** [comment]
\>SpeedX explained why bomber.py was encrypted...

For your information, API endpoints can't tell whether their malicious usage was initiated by TBomb or any other application alike. Of course, they can determine whether that usage is malicious or not in the first place, but then it's unaffected by TBomb's being open-source or not.

I *highly* doubt that *any* of the API providers even acknowledge that they were used particularly by the TBomb.

**Comment by 0n1cOn3** [comment]
> For your information, API endpoints can't tell whether their malicious usage was initiated by TBomb or any other application alike. Of course, they can determine whether that usage is malicious or not in the first place, but then it's unaffected by TBomb's being open-source or not.
> 

We are not specifically concerned with API validation here, but with the release of bomber.py (TBomb) as an open source file itself. And the warning that TBomb is being abused was mentioned several times in those days. 

Now we are so far that this project has a large audience, but is no longer useful for anything.

I see so many projects on Github where the files are already precompiled. And there is no fuss about the source code.

So I can't understand why you pushed SpeedX until he MUST release it decrypted.

**Comment by scpketer** [comment]
Reconsider my 'just as planned' once again, boy.

**Comment by 0n1cOn3** [comment]
> Reconsider my 'just as planned' once again, boy.

I do not understand

**Comment by scpketer** [comment]
\>Oh noes, TBomb is dead after a year
\>Just as planned.

Once. Again.

**Comment by scpketer** [comment]
Leaving now, contact via Telegram/E-mail, I'm outta here.

**Comment by TheSpeedX** [comment]
The code has been updated and this issue serves no further purpose.
