### ISSUE TITLE
How to prevent

### ISSUE THREAD

**Issue by vklnnr** [TheSpeedX/TBomb#149]
I keep getting call bombs and sms boms for 4 months how do i stop it

**Comment by 0n1cOn3** [comment]
Theres no way to prevent it.

**Comment by TheSpeedX** [comment]
use OTP Blocker and activate DND

**Comment by vklnnr** [comment]
I activated dnd but i still get calls i dont know how..please help...i am seriously frustrated

**Comment by vklnnr** [comment]
Now i get 100+ calls daily
