### ISSUE TITLE
Please update SMS list in your py file

### ISSUE THREAD

**Issue by AlistairXX** [TheSpeedX/TBomb#150]
Just read your code...That's very smart to use companies weapons against users. 

Just saw after imputing the number the number is then used on said websites like flipkart etc to send texts...what if we added 10 more sites...I can provide with the links...as it's open-source and anyone can add but imagine 10-20 people providing links for sms based login websites...

Make this thing ultra uber devastating.

**Comment by 0n1cOn3** [comment]
Thank you for those words. Unfortunately I don't know how to search for these APIs myself.

You are very welcome to support us and become a part of Tbomb.

**Comment by trwolff04** [comment]
AlistairXX, I am interested in this as well.  Can you elaborate on how to modify to and add API's?

**Comment by 0n1cOn3** [comment]
@trwolff04 Check out the dev branch for more and better overview ;-)

**Comment by TheSpeedX** [comment]
New Added added in #190
