### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by MRFOX777** [TheSpeedX/TBomb#156]
SMS/Call bombing not work in Bangladesh
Plz solve this

**Comment by Nimish279** [comment]
What error you're getting?

**Comment by 0n1cOn3** [comment]
Please provide more details about this issue. 

- Screenshot
- Error Description 
- Screenshot with an Ping Test

**Comment by TheSpeedX** [comment]
Fix in #190

**Comment by leorafsan1** [comment]
![Screenshot_2023-05-07-10-46-57-513_com termux](https://user-images.githubusercontent.com/109914736/236658157-7a51881c-34a8-4cd4-8ec5-0ce42eca1d86.jpg)
Not working

**Comment by 0n1cOn3** [comment]
> ![Screenshot_2023-05-07-10-46-57-513_com termux](https://user-images.githubusercontent.com/109914736/236658157-7a51881c-34a8-4cd4-8ec5-0ce42eca1d86.jpg) Not working

I dont know why you posting this:

1) Its not a bug
2) This issues has already been closed
3) RTFM!

![grafik](https://user-images.githubusercontent.com/27576311/236851455-6d2dcfd1-8ed9-4eb7-b2cb-10e02a25fdc2.png)
