### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by EpicSamar360** [TheSpeedX/TBomb#16]
The Verification process is literal Bullshit. Just remove it, there's already a limit on the number of messages so Just remove the Verification process because it takes 10 minutes to complete with all the spam pop up ads saying that I have a virus on my computer. Fuck that

**Comment by 0n1cOn3** [comment]
I dont see any problem. i have only few seconds till i have the verificaton code. 
Also this is a security option for misuse or use a bot instead to be a human to execute TBomb.

tip:

- open the link for the verification code.
- click on "get link" and close the openend window.
- click again on "get link" and you have your code

#Closed

**Comment by crinny** [comment]
@EpicSamar360 you could delete this crap manually. Source code is [here](https://github.com/crinny/TBombDeobfuscated)

**Comment by TheSpeedX** [comment]
@crinny Please As You are A Developer I Think You Support You Please Remove Your For To Prevent Misuse And Making API Dead ...

Hope You Understand

**Comment by TheSpeedX** [comment]
@EpicSamar360 Please see https://drive.google.com/file/d/1LrfmhTXKOlEU3RRmNtXFRXdUPnpN323s/view?usp=drivesdk
