### ISSUE TITLE
Unable to start bombing

### ISSUE THREAD

**Issue by imanjatt** [TheSpeedX/TBomb#17]
I am unable to start bombing it says 
Taceback error on kali linux and python2 not found on termux but i have installed python 2 in termux.

**Comment by TheSpeedX** [comment]
If you are using TBomb in Kali Nethunter in Termux 
Then   Install then installl the packages in TBomb.sh manually in Nethunter

apt install python3 python2 
apt install python3-pip python3-requests

**Comment by Bhatyawar** [comment]
Give the packages of TBomb attack through termux for android

**Comment by TheSpeedX** [comment]
just clone the code and use
see the reeuirements.txt

**Comment by 9827272121** [comment]
Only pip install requirements --user is said in termux what to do

**Comment by 0n1cOn3** [comment]
Please let us a Screenshot here, when this problem appear.

From Kali & Termux
