### ISSUE TITLE
How To Get Rid of This tool

### ISSUE THREAD

**Issue by AmshenShanu07** [TheSpeedX/TBomb#178]
So Many people is misusin this tool plzz provide a method to get rid of these typs bof tools

**Comment by Y964** [comment]
sudo su
chown -v user TBomb

**Comment by 0n1cOn3** [comment]
@Y964 Thats not the prober solution. He may ask, how to get the ride off from receiving OTP Messages.

**Comment by TheSpeedX** [comment]
You could use OTP Blockers and activate DND.
