### ISSUE TITLE
please remove otherwise added protect list

### ISSUE THREAD

**Issue by udit1049** [TheSpeedX/TBomb#186]
please remove otherwise added protect list

**Comment by lucifer874** [comment]
What is protection list

**Comment by udit1049** [comment]
Daily 10k otp received in my mobile this script throught remove this script other wise send me your number i am send otp form this script throght that your know this script is not help full

**Comment by 0n1cOn3** [comment]
@udit1049 You have been reported for spamming. 

This is not a feature request area.

**Comment by udit1049** [comment]
Remove this script please bcz all people send otp me otherwise i am reported

**Comment by udit1049** [comment]
And i am not said any request clearly remove this script please

**Comment by nitish0229** [comment]
What should I remove..I couldn't understand anything?. What are u saying dude

**Comment by 0n1cOn3** [comment]
@udit1049 

**This** is a developer platform and not a wish concert what you want or not.** 
If you want a protection list, program one and send it via PR.

**Comment by udit1049** [comment]
this is devloper platform but this script used all local people send me your number that i am said this is devloper script noob

**Comment by 0n1cOn3** [comment]
There will be a good reason why.

**Comment by 0n1cOn3** [comment]
@TheSpeedX Can be closed.. All Tickets from @udit1049

**Comment by udit1049** [comment]
Noobdly not send any answer and direct close why??

**Comment by TheSpeedX** [comment]
`Protection List` can not be added for the following reasons:
- Code is opensource.
- The APIs used by us is not owned by us.
- Only possible protection would be from client side which can be bypassed easily.

So , unless you have an idea of how we could integrate `Protection List` without using our own servers, this PR will be remain closed.
