### ISSUE TITLE
Syntax error, could not install dependencies

### ISSUE THREAD

**Issue by trwolff04** [TheSpeedX/TBomb#196]
~~~
Introducing TBomb
 This Bomber Was Created By SpeedX 
 For Any Queries Mail Me!!!
           Mail: ggspeedx29@gmail.com 
   YouTube: https://www.youtube.com/c/GyanaTech 
 
Press any key to continue...
awk: syntax error at source line 1
 context is
	match($0, >>>  "(.+?)[-_](?:release|version)", <<< 
awk: bailing out at source line 1
Installing Requirements....
.
.
We could not install dependencies.
Please make sure you have git, python3, pip3 and requirements installed.
Then you can execute bomber.py .
~~~

**Comment by trwolff04** [comment]
Running on osx mojave, followed directions, installed all dependencies.  sudo easy_install pip returned an error though.

**Comment by 0n1cOn3** [comment]
Did you installed brew aswell? If not, install brew and install from brew python3 

brew install python3.8

**Comment by abdoelfek** [comment]
> Did you installed brew aswell? If not, install brew and install from brew python3
> 
> brew install python3
> 
> Then, the pip or pip3 is installed automatically, and you can install any package by "pip install package" 
I can not understand 
Can you tell me how please ?

**Comment by TheSpeedX** [comment]
@abdoelfek Can you explain your issue?

**Comment by Arsh84** [comment]
> @abdoelfek Can you explain your issue?

I have the same issue that... TBomb cannot install dependencies . Can u help me solve this issue.

**Comment by TheSpeedX** [comment]
Kindly use the pip version

**Comment by DRKxJIN** [comment]
Please make sure you have git, python3, pip3 and requirements installed.
this error shows when I try to install this
