### ISSUE TITLE
Custom sms

### ISSUE THREAD

**Issue by Palmus84** [TheSpeedX/TBomb#2]
Hi
is there a way for customize sms?

**Comment by TheSpeedX** [comment]
Sorry Customized SMS Are Paid So We Cant Integrate For international Use 

But we will do it if we could

Thanks For Supporting My Project

**Comment by PrixHacks** [comment]
CAN YOU ADD CUSTOM SMS FOR INDIAN USERS

**Comment by TheSpeedX** [comment]
Custom SMS Would Cost Me

But If i found any vulnerable sites I Will Add

Lets Wait For Future Updates

**Comment by TheSpeedX** [comment]
Closed #2
