### ISSUE TITLE
Call Bombing not working!!!

### ISSUE THREAD

**Issue by BonnY0** [TheSpeedX/TBomb#200]
Call Bombing is not working for Bosnia +387 pls fix

**Comment by 0n1cOn3** [comment]
Call Bombing is only for India.

**Comment by wildwolf01-star** [comment]
> Call Bombing is only for India.

But its not working in india (+91)

**Comment by chankruze** [comment]
> > Call Bombing is only for India.
> 
> But its not working in india (+91)

Run the script, enter your number and record your phone, share that recording.

**Comment by TheSpeedX** [comment]
Duplicate of #198
