### ISSUE TITLE
Not working for mexican numbers

### ISSUE THREAD

**Issue by donmetapod** [TheSpeedX/TBomb#203]
This is a great tool, SMS bombing works perfectly but Calls and email are not working I get the message "Your country/target is not supported as of now Feel free to reach out to us"

**Comment by 0n1cOn3** [comment]
Phone Bomb is only for India. 

Mail Bomb is not yet fully implemented. But will be added asap.

**Comment by donmetapod** [comment]
Thanks for the replay, I'll try Mail Bomb as soon as is available.

**Comment by t0xic0der** [comment]
I think we can safely close this issue. The conversation has been resolved.
