### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by rocksT-H** [TheSpeedX/TBomb#207]

**Comment by t0xic0der** [comment]
@0n1cOn3 please shut down this issue.

**Comment by 0n1cOn3** [comment]
@t0xic0der i can't ;(

**Comment by rocksT-H** [comment]
> @t0xic0der i can't ;( 

Check gamer tech330 on YouTube

**Comment by 0n1cOn3** [comment]
> > @t0xic0der i can't ;(
> 
> Check gamer tech330 on YouTube

What?
