### ISSUE TITLE
Add +20 For Egypt

### ISSUE THREAD

**Issue by AmrWassiem** [TheSpeedX/TBomb#215]
I want to spam in some one can you put Egypt country code for me please ? 🤗
are you going to add it ? 🇪🇬
our calls company is Vodafone:
https://web.vodafone.com.eg/en/home

**Comment by AmrWassiem** [comment]
Egypt country code is:
+20

**Comment by TheSpeedX** [comment]
The country code is already in the isdcodes.
If you mean adding by adding to Call Bomb, There are no international api for call bomb yet. But SMS Bomb is available

**Comment by Volcano69** [comment]
Why Not
But First You need to send me all information
with identity card
