### ISSUE TITLE
Bomber is finally cracked.

### ISSUE THREAD

**Issue by darkestentropy** [TheSpeedX/TBomb#22]
I've been spectating this repo (as well as the drama behind issue #19, thanks a lot for bringing this topic up, @scpketer), and took my courage to create a thing that will finally pry open your `bomber.py`

Behold! https://github.com/darkestentropy/bombcrack. A thing that will let everyone take a look what's inside a toy of yours.

Watch it - MIT license allows me to freely modify and redistribute software licensed under. And here it comes.

About all of your 'warnings' - they are worthless, because (a quote):
>TBomb in its current state is already a tool that is capable of dealing damage

**Comment by TheSpeedX** [comment]
Hello 
I know you are a developer like me..

i hope that you analyzed the code and i am sure you can say that there is no malware hidden  as @scpketer said

And you currently know the security concerns if it will be used without any limits 

So i request you to kindly take it down

I know its an easy obfuscation as maintaining  TBomb by adding new APIs became harder for me 
So i did not much really care to obfuscate it more

Hope That You will umderstand

Any issues feel free to ping...

**Comment by scpketer** [comment]
Finally. Someone!

**Comment by TheSpeedX** [comment]
@scpketer Few others decoded too
He is not the first but i appreciate the efforts

But others too took it down

If u want u can keep for personal use but please don't spread

I think you know its consequences ...
If someone will bomb you without any limit....

**Comment by EVRICA** [comment]
darkestentropy     If bomber.py really contains APIs and other important information you should understand there is possibility that Tbomb will stop working soon. It could be damaged, broken or somesing else by someone just with your code. You should just tell us whether bomber.py safe or not and delete your repo. You don't want Tbomb to be broken, do you? Otherwise we all lose Tbomb.

**Comment by darkestentropy** [comment]
@EVRICA, TBomb is [licensed under MIT license](https://github.com/TheSpeedX/TBomb/blob/master/LICENSE). Let's see what is allows:
* Code redistribution
* Code modification

That means **I'm free** to do any of the actions above. If @TheSpeedX had to create a closed-source application, they had to host it somewhere else and license under something else.

#### I'm not deleting my repository under any conditions.

**Comment by TheSpeedX** [comment]
@EVRICA I have no issue with @darkestentropy 
As he is not distributing source directly...

And anyway i was going to open source it sooner or later

Thanks @EVRICA  @darkestentropy @scpketer For Your Support

**Comment by darkestentropy** [comment]
*DarkestEntropy quits the converation*

For problems related to bombcrack's implementation - please post issues in bombcrack's [issues section](https://github.com/darkestentropy/bombcrack/issues). 
For problems related to TBomb - please open [another issue](https://github.com/thespeedx/tbomb/issues/new).

**Comment by TheSpeedX** [comment]
@darkestentropy I have Changed The License Of TBomb 

So regarding it I am requesting you to Take bombcrack down 

Hope that You will understand and not take it in a negative way
