### ISSUE TITLE
TheSpeedX/TBomb not working

### ISSUE THREAD

**Issue by Zack-sys** [TheSpeedX/TBomb#231]
"We could not install dependencies.
Please make sure you have git, python3, pip3 and requirements installed.

Then you can execute bomber.py"

That what it says but I already download it!?

**Comment by JosephCordero** [comment]
Im having the same issue

"We could not install dependencies.
Please make sure you have git, python3, pip3 and requirements installed."

**Comment by TheSpeedX** [comment]
Kindly use the pip version.
