### ISSUE TITLE
Limited Unleash Limited

### ISSUE THREAD

**Issue by kumar227** [TheSpeedX/TBomb#236]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Mint]
 - Terminal [e.g. bash, WSL, cygwin]
 - Python Version [e.g. 3.5, 3.8]

**Smartphone (please complete the following information):**
 - Terminal [e.g. iSH, Termux]
 - Python Version [e.g. 3.5, 3.8]

**Additional context**

**Comment by kumar227** [comment]
Update it unlimited

**Comment by 0n1cOn3** [comment]
Due the amount of limite, TBomb will run for a long time. Without, the Project dies asap.

**Comment by 0n1cOn3** [comment]
@TheSpeedX 

Can be closed
