### ISSUE TITLE
I’m stuck at this 

### ISSUE THREAD

**Issue by faizu-17** [TheSpeedX/TBomb#238]
![53BA032C-1BA7-4382-980E-4291D1E96886](https://user-images.githubusercontent.com/76480881/103156322-8d55a480-47cd-11eb-8bc3-07679d90991a.png)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by faizu-17** [comment]
![Uploading 47B682D6-C61C-49E7-B3BA-E2C1304BCFBA.png…]()

**Comment by TheSpeedX** [comment]
Kind use the pip version.
Check the README for how to do so.
