### ISSUE TITLE
Not working in Kenya +254

### ISSUE THREAD

**Issue by HackWeiser360** [TheSpeedX/TBomb#239]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Mint]
 - Terminal [e.g. bash, WSL, cygwin]
 - Python Version [e.g. 3.5, 3.8]

**Smartphone (please complete the following information):**
 - Terminal [e.g. iSH, Termux]
 - Python Version [e.g. 3.5, 3.8]

**Additional context**

**Comment by 0n1cOn3** [comment]
@TheSpeedX 

Can be closed - Its not a correct filled form.
