### ISSUE TITLE
leeds 2 scam site

### ISSUE THREAD

**Issue by 9-s3c** [TheSpeedX/TBomb#24]
lmao, took me 5 minutes to deobfuscate your code,
but anyone without those skills is stuck with having to go get a "verification" from your shitty scam site

**Comment by 9-s3c** [comment]
im assuming your another fucking Indian scammer

**Comment by TheSpeedX** [comment]
I dont own that ad site

I just use ads to controller user

No one is getting scammed
Neither i charge you nor you give any personal info

You can see this video of getting how to solve it
https://gofile.io/?c=siVuMi

I know the obfuscation is pretty weak 
And i will make the code open source soon...

> im assuming your another fucking Indian scammer

I guess you decrypted the code right...
Then Now also if u think that code is a scam 

Then either you are high dude @9-s3c  So please Take care of what you speak

**Comment by 9-s3c** [comment]
if u want better obfuscation just compile it to a binary file

**Comment by TheSpeedX** [comment]
But it wont be compatible is cross platform..

And btw i will release the source soon too

So i will not get into that issue...
