### ISSUE TITLE
YDV 


### ISSUE THREAD

**Issue by aman143431** [TheSpeedX/TBomb#242]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Mint]
 - Terminal [e.g. bash, WSL, cygwin]
 - Python Version [e.g. 3.5, 3.8]

**Smartphone (please complete the following information):**
 - Terminal [e.g. iSH, Termux]
 - Python Version [e.g. 3.5, 3.8]

**Additional context**

**Comment by 0n1cOn3** [comment]
@TheSpeedX Can be closed

Just another spam

**Comment by aman143431** [comment]
> @TheSpeedX Can be closed
> 
> Just another spam

Sorry bro
