### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by Xanaxus** [TheSpeedX/TBomb#244]
**Describe the bug**
Unable to execute and I have the latest python version

**To Reproduce**
Running on PopOS! 

**Expected behavior**
it to run

**Screenshots**
![image](https://user-images.githubusercontent.com/53279068/104345542-7b416900-5524-11eb-86cf-01c2e8632228.png)

**Desktop (please complete the following information):**
 - OS: Linux - popos!
 - Terminal: Fish
 - Python Version  3.8.6

**Comment by 0n1cOn3** [comment]
DId you tried with "pip3 install -r requirements.txt" inside the folder?

**Comment by TheSpeedX** [comment]
@Xanaxus Kindly use the PIP version
