### ISSUE TITLE
I cant use bombing in NetHunter....

### ISSUE THREAD

**Issue by 8519033846** [TheSpeedX/TBomb#251]
![Screenshot_20210205_213658_com termux](https://user-images.githubusercontent.com/78609739/107058810-144d6200-67fb-11eb-8e56-a79c30732e85.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Mint]
 - Terminal [e.g. bash, WSL, cygwin]
 - Python Version [e.g. 3.5, 3.8]

**Smartphone (please complete the following information):**
 - Terminal [e.g. iSH, Termux]
 - Python Version [e.g. 3.5, 3.8]

**Additional context**

**Comment by Deepakcybe** [comment]
Yes

**Comment by t0xic0der** [comment]
@0n1cOn3 @TheSpeedX There's something messed up with the SH file I think. Please take a look.

**Comment by TheSpeedX** [comment]
Well, it shows different behavior in different environment. It's better to switch to pip version(check README for details). 
Or you can install dependencies manually and run directly.
