### ISSUE TITLE
Why is there limit of 15 calls and 500 messages and from that 15calls only one works!!

### ISSUE THREAD

**Issue by neonbeast** [TheSpeedX/TBomb#256]
![IMG_20210222_172205](https://user-images.githubusercontent.com/66249437/108704808-85e31b00-7532-11eb-945b-d274e192cd5c.jpg)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by neonbeast** [comment]
> ![IMG_20210222_172205](https://user-images.githubusercontent.com/66249437/108704808-85e31b00-7532-11eb-945b-d274e192cd5c.jpg)
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

Why there's limit of 15 calls?

**Comment by neonbeast** [comment]
![Uploading IMG_20210222_173129.jpg…]()

Also it's is saying bombing completed but I didn't got a single call!!

**Comment by 0n1cOn3** [comment]
Please fill out the formula. Without it, there will be no answer given.

Thanks

**Comment by TheSpeedX** [comment]
This is due to API limits. This isn't an issue in codebase.
