### ISSUE TITLE
We could not install dependencies. [Ubuntu 18.04]

### ISSUE THREAD

**Issue by steelx** [TheSpeedX/TBomb#257]
**Describe the bug**
I just ran the script with all the dependencies installed with 
`pip3 install -r requirements.txt `

**Screenshots**
![image](https://user-images.githubusercontent.com/3184210/108949082-bb4e4c80-7689-11eb-99ef-cebf759cf959.png)

**Desktop (please complete the following information):**
Linux zorinos 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

 - Python3 Version : 3.9
 - Python version : 2.7.17

**Additional context**
I have both pip3 and pip installed, as well git. and python3 and python

**Comment by TheSpeedX** [comment]
Can you try `pip3 install tbomb` and run `tbomb` directly

**Comment by steelx** [comment]
> Can you try `pip3 install tbomb` and run `tbomb` directly
Thanks for revert.
I  need to run from source code.

**Comment by kartikeysingh6** [comment]
I'm getting the exact same error, Everything is install each requirement still it gives "We could not install dependencies". I also did pip3 install tbomb but it shows "command tbomb not found"
