### ISSUE TITLE
Call Bombing not working

### ISSUE THREAD

**Issue by rebel47** [TheSpeedX/TBomb#258]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 0n1cOn3** [comment]
Unnecessary

**Comment by kuzuri-03** [comment]
it's not working 
call bomber not working for india 
not even 1 call has been made by that script

**Comment by kingmakerisback** [comment]
ya bro this tool not working please help us

**Comment by OscarEscobar666** [comment]
This shit is not working
