### ISSUE TITLE
No sms's being send

### ISSUE THREAD

**Issue by lolJeremyFTW** [TheSpeedX/TBomb#259]
**Describe the bug**
when i start the scripts I'm getting really few sms's, like when i select 100 sms's im only recieving 1 sms and a call. even tought the software says it has a lot of successful hits(there is usually 20-40 out of 100 that says are hits

**To Reproduce**
start the script, select 1(sms), country code +31, any amount of sms and threads, i tried delay between 0.1 and 25 seconds

**Expected behavior**
i kinda expected a higher succes rate

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Mint]
     -Kali linux
 - Terminal [e.g. bash, WSL, cygwin]
     -qterminal
 - Python Version [e.g. 3.5, 3.8]
    -3.9.1

**Comment by 0n1cOn3** [comment]
We're ware about that. We will push soooooooon an update to fix several API issues

**Comment by lolJeremyFTW** [comment]
i appriciate the quick response, thanks for the update! atleast i know its not on my end now haha
