### ISSUE TITLE
Fully support for jailbroken Apple devices

### ISSUE THREAD

**Issue by 0n1cOn3** [TheSpeedX/TBomb#262]
After testing TBomb on jailbroken devices, i can say: TBomb is fully compatible. 

python3 install ensurepip
pip3 install --upgrade pip
pip3 install TBomb

Start TBomB: tbomb

**Comment by 0n1cOn3** [comment]
![image](https://user-images.githubusercontent.com/27576311/109802598-4f875900-7c20-11eb-9eab-5247c512d5d8.png)

**Comment by TheSpeedX** [comment]
This could be added in README in iSH section if you wish
Closing the isssue.
