### ISSUE TITLE
Can you add america's area code? (+1)

### ISSUE THREAD

**Issue by Joshii01** [TheSpeedX/TBomb#270]
Hello there @TheSpeedX ! i currently am trying to run this in the USA and it says it isnt supported. can you please add the +1 area code please? thanks! <3

**Comment by 0n1cOn3** [comment]
Thank you for your information! We had in the past several APIs. But they are nowadays invalid. We're expect an API Update within they few days. 

Sincerly 

0n1cOn3

**Comment by Joshii01** [comment]
Ok! thank you very much man. have a great rest of your day. :D
