### ISSUE TITLE
TBomb is not working on Termux app!!

### ISSUE THREAD

**Issue by Lucifer-00007** [TheSpeedX/TBomb#271]
**Error message**:-
```
File "/data/data/com.termux/files/home/TBomb/bomber.py", line 17, in <module>
    from utils.decorators import MessageDecorator
ModuleNotFoundError: No module named 'utils.decorators'
```

**To Reproduce**
```
- git clone  https://github.com/TheSpeedX/TBomb.git
- pip install -r requirements.txt
- cd TBomb
- python bomber.py  
- bash TBomb.sh (Or directly)
```

**Expected behavior**
To do exactly what it is meant for!!

**Screenshots**
![Screenshot_2021-03-30-21-40-05-324_com termux](https://user-images.githubusercontent.com/57388389/113021244-0552b280-91a1-11eb-84e0-585512e39f17.jpg)

**Smartphone (please complete the following information):**
 - Device: [Poco F1]
 - OS: [Android 10]
 - Terminal: [Termux]
 - Python Version: [3.9.1]

**Comment by 0n1cOn3** [comment]
Give a try with:

pip3 install TBomb

**Comment by Lucifer-00007** [comment]
> Give a try with:
> 
> pip3 install TBomb


Your solution is working , thank you.
But i also want to know what is issue in the process i have done [above](https://github.com/TheSpeedX/TBomb/issues/271#issue-844814245)

**Comment by TheSpeedX** [comment]
That was an issue in code found in some systems.

**Comment by gokul335** [comment]
pip3 install TBomb command also not working bro please help me
