### ISSUE TITLE
Mohammed Ibrahim 

### ISSUE THREAD

**Issue by mohammedibrahim18** [TheSpeedX/TBomb#275]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Mint]
 - Terminal [e.g. bash, WSL, cygwin]
 - Python Version [e.g. 3.5, 3.8]

**Smartphone (please complete the following information):**
 - Terminal [e.g. iSH, Termux]
 - Python Version [e.g. 3.5, 3.8]

**Additional context**

**Comment by mdshiful** [comment]
THANKS

**Comment by 0n1cOn3** [comment]
No useful infos. Please edit it or close the issue. 


Thanks
