### ISSUE TITLE
[ ✘ ] Poor internet connection detected

### ISSUE THREAD

**Issue by shahidabro93** [TheSpeedX/TBomb#293]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 0n1cOn3** [comment]
Hello

Please don't use the formula to give some bad words. Aswell, don't abuse this function, what you actually did! Read the FAQ and the first lines of the README before you open a ticket! 

Sincerly 

0n1cOn3
