### ISSUE TITLE
Verification Link Error

### ISSUE THREAD

**Issue by dominionman12** [TheSpeedX/TBomb#30]
I cloned TBomb on Ubuntu 18.04. 
When I was ready to test the script it asked to to verify but asking me to go to a link and putting the code back into the terminal.
The website has no code 
What should I do? 
![TBOMB-verification](https://user-images.githubusercontent.com/29575183/64990207-5b048a00-d89d-11e9-8168-f7c26d21a373.png)

**Comment by TheSpeedX** [comment]
https://gofile.io/?c=siVuMi
Please view this to get the code
Also see #21
