### ISSUE TITLE
TBomb GUI

### ISSUE THREAD

**Issue by ElskerElvish** [TheSpeedX/TBomb#317]
Herer is something exciting.. GUI version of TBomb..... 

https://github.com/ElskerElvish/TBomb_GUI

**Comment by ayushshaw90** [comment]
GUI versions don't work on termux. Anyways, your work is appreciated.

**Comment by ElskerElvish** [comment]
As it uses tkinter library ( which is not for android.. ) so it won't work in android..

**Comment by 0n1cOn3** [comment]
Maybe with ncurses it would work 🤔😊
