### ISSUE TITLE
Verifying You ...         Please Have Patience...                   Sorry To Interrupt !!!  But Due To Heavy Requests To TBomb We Need To Verify You ... You Just Need To Go To This Link:                   

### ISSUE THREAD

**Issue by IGotHacked999** [TheSpeedX/TBomb#32]
` Verifying You ...
        Please Have Patience...

                Sorry To Interrupt !!!

But Due To Heavy Requests To TBomb We Need To Verify You ...
You Just Need To Go To This Link:

                https://gplinks.in/gEtKU6

And Enter The Code Here
Code:`
![image](https://user-images.githubusercontent.com/55454039/65261984-fca90700-db3b-11e9-9261-4aefb85cbcc9.png)

**Comment by normie5-cell** [comment]
Really

**Comment by WrongProgram1** [comment]
This isn't a PROBLEM :/

**Comment by werewolf3097** [comment]
> This isn't a PROBLEM :/

so? what is that ? I can't understand...cause I go with the link into browser, and when captcha verified me, I' got nothing.

**Comment by TheSpeedX** [comment]
@IGotHacked999 @normie5-cell @werewolf3097 @WrongProgram1 

Please Check the video here to see how to get code
https://gofile.io/?c=siVuMi
