### ISSUE TITLE
ValueError: could not convert string to float:

### ISSUE THREAD

**Issue by WrongProgram1** [TheSpeedX/TBomb#33]
![image](https://user-images.githubusercontent.com/49438078/65366114-39ffb880-dc52-11e9-8552-82e3f542b205.png)

**Comment by WrongProgram1** [comment]
How?

**Comment by KingRanger984** [comment]
Bro if you input any Character then how is it possible that it will become a float? Enter integers or floats only like - 4, 4.0 etc

**Comment by TheSpeedX** [comment]
Thanks @KingRanger984 

I think @WrongProgram1 Your confusion is cleared
Input number of messages not what the message is
