### ISSUE TITLE
Human verification

### ISSUE THREAD

**Issue by mikkyboy2005** [TheSpeedX/TBomb#34]
The human verification function in the program is absolutely unnecessary.
And it also make is inconvenient to use the program.
The human verification is cumbersome in nature and the link where the verification code can be found is impossible for some users to find.
-- mikkyboy2005@gmail.com
-- mikkyboy2005@github.com
                                        Michael.

**Comment by TheSpeedX** [comment]
@mikkyboy2005  There are users over using TBomb .
So I had to put Adlinks To Prevent Maximum Usage Of The Tool

Please Check the video here to see how to get code
https://gofile.io/?c=siVuMi
