### ISSUE TITLE
So bad sorry but it doesn't work at all and doesn't send anything! lol

### ISSUE THREAD

**Issue by Bezdna7** [TheSpeedX/TBomb#346]
So bad sorry but it doesn't work at all and doesn't send anything! lol
+79 000 000 0 
ru number dont work

**Comment by 0n1cOn3** [comment]
We are aware of this and apologise for the current state. @TheSpeedX announcend an update for January 2022. 
Let's see if this have further API improvements 😛

**Comment by Bezdna7** [comment]
> We are aware of this and apologise for the current state. @TheSpeedX announcend an update for January 2022. Let's see if this have further API improvements stuck_out_tongue

thanks!
