### ISSUE TITLE
BOMBING APIS 

### ISSUE THREAD

**Issue by xlr88888** [TheSpeedX/TBomb#348]
https://xxl02.herokuapp.com/BOMB/NUMBER
https://xxl03.herokuapp.com/BOMB/NUMBER
https://xlr73.herokuapp.com/BOMB/NUMBER

**Comment by xlr88888** [comment]
@TheSpeedX

**Comment by xlr88888** [comment]
IT CAN ONLY BOMB INDIAN NUMBERS

**Comment by 0n1cOn3** [comment]
If you have seen bomber.py and how it's setup... You may know that this will not work until a method has been implemented

**Comment by xlr88888** [comment]
@0n1cOn3 did you try the bombing apis they are good

**Comment by 0n1cOn3** [comment]
I actually don't know how to implement them properly🥲

**Comment by xlr88888** [comment]
@0n1cOn3 
this is easy to implement


echo "enter target number:"
read target
curl https://xxl02.herokuapp.com/BOMB/$target

**Comment by 0n1cOn3** [comment]
Gonna test this and will let you know if we can add this as it is 😎👌🏻

**Comment by TheSpeedX** [comment]
@xlr88888 Thanks for the API Link, but those Heroku instances seems to be down. Feel free to open a new PR or Issue when you have more APIs to share.
