### ISSUE TITLE
Too many failed request when importing tbomb.workernode for making other project 

### ISSUE THREAD

**Issue by Zaeem20** [TheSpeedX/TBomb#369]
Hey TheSpeedX,

i am trying to customizing tbomb , and using tbomb,workernode in my project but as compare to TBomb tool i am getting too many failed request, but in TBomb it is very less why is it so....

**Comment by 0n1cOn3** [comment]
Hi

I can reply in the name of SpeedX.
As already mentioned in the README.md, previous TBomb Users abused the API's.
Thats why u see "successfull" instead of failed. Cause only the requests gonna be checked but not if the Content has been delivered.

**Comment by Zaeem20** [comment]
> Hi
> 
> I can reply in the name of SpeedX. As already mentioned in the README.md, previous TBomb Users abused the API's. Thats why u see "successfull" instead of failed. Cause only the requests gonna be checked but not if the Content has been delivered.

no but when i use tbomb for sms bombing it giving me less number of failed request but when i use tbomb.workernode in my another package it giving many failed request

**Comment by Zaeem20** [comment]
@0n1cOn3 see i have some ss for quick comparision

i had setup this tbomb.workernode in my project 

![image](https://user-images.githubusercontent.com/60778335/169690144-7a62bae8-6713-4dea-9e47-4146f197fb8b.png)

here you can clearly see how many failed request are going for just 10 sms 
<hr>

And here is a ss of normal tbomb package on same number

![image](https://user-images.githubusercontent.com/60778335/169690373-eaa94b21-5a62-4d63-b5e3-df4c47d0a4c3.png)

see here you can clearly see the difference

why is it so....

**Comment by TheSpeedX** [comment]
Maybe some API are rate-limiting you. Add sufficient intervals between calls to the same API.

As you have not shared your code it's difficult to debug and the issue is unrelated to TBomb as well.
You can discuss more in Telegram Group in Contact Section
