### ISSUE TITLE
HELP ME 

### ISSUE THREAD

**Issue by pablomontas** [TheSpeedX/TBomb#37]
I have that problem 

https://subefotos.com/ver/?1e86da03de5a4cb5129e04a71c8240e9o.jpg

 please help me

**Comment by TheSpeedX** [comment]
@pablomontas Please Specify What inputs u gave

**Comment by Aswin-0squirrel** [comment]
what is code ?\

**Comment by pablomontas** [comment]
https://subefotos.com/ver/?f6061e3383c2e980cd7f9bb4ba02445eo.png#codigos

https://subefotos.com/ver/?4f2f30636b60bb266807c11425927162o.png#codigos

here is the problem

**Comment by ViperZCrew** [comment]
Issue is known

**Comment by 0n1cOn3** [comment]
oh, ups wrong Account xD

**Comment by pablomontas** [comment]
So, how can i fix the problem?

**Comment by vishnudk** [comment]
they are asking for verification code 
but the link provided is not working

**Comment by pablomontas** [comment]
I put the link well, and the verification code correctly

**Comment by TheSpeedX** [comment]
@pablomontas Please CAn u say what ur country is
 google what ur country codeis and try again 

the issue u are getting is due to invalid country code

**Comment by TheSpeedX** [comment]
@vishnudk  @Aswin-0squirrel 

To Get The Please Follow The  Video tut downloadable right at 

https://gofile.io/?c=siVuMi

Dont misjudge the script just for the verification thing its there to decrease TBomb load

**Comment by pablomontas** [comment]
I'm from Dominican Republic, and the code is 829 or 809

**Comment by TheSpeedX** [comment]
@pablomontas  I guess you were confused area code with country code

Try Putting 1 in Country code and remaining digits in phone number 

I guess this will solve so i am closing issue
