### ISSUE TITLE
Not installing git -y package 

### ISSUE THREAD

**Issue by ravikiran3021** [TheSpeedX/TBomb#375]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Mint]
 - Terminal [e.g. bash, WSL, cygwin]
 - Python Version [e.g. 3.5, 3.8]

**Smartphone (please complete the following information):**
 - Terminal [e.g. iSH, Termux]
 - Python Version [e.g. 3.5, 3.8]

**Additional context**
Not installing git -y package in termux

**Comment by TheSpeedX** [comment]
Not related to TBomb 

Install Termux From F-Droid use correct sources to install git.

Refer: https://github.com/TheSpeedX/TBomb#install-by-pip-recommended to install without Git
