### ISSUE TITLE
Not send sms to vietnam phone number

### ISSUE THREAD

**Issue by kimpro12** [TheSpeedX/TBomb#382]
**Describe the bug**
it doesn't send SMS to vietnam phone number

**To Reproduce**
I enter vietnam phone number

**Expected behavior**
FIx

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04, Window 10]
 - Terminal [bash]
 - Python Version [3.9.2]
 - 
**Additional context**
Hopely you will fix it
![tbomb](https://user-images.githubusercontent.com/95573884/184546025-b78facf7-8178-44f4-9755-9ab66fa4704e.png)

**Comment by 0n1cOn3** [comment]
No Vietnam API available, sorry.
