### ISSUE TITLE
Code? 

### ISSUE THREAD

**Issue by Kohinoorr** [TheSpeedX/TBomb#39]
Your script is asking for a code for verification... And to open a link to get the code but there is no code on the... Link and u have also hidden the captcha... So can you provide the code to launch your script.

**Comment by TheSpeedX** [comment]
See @Kohinoorr I have to do that verification thing due to heavy usage and misuse of TBomb...

If you wanna know how to get the code you can check the video https://gofile.io/?c=siVuMi
