### ISSUE TITLE
Not Working at all!

### ISSUE THREAD

**Issue by nafisshagor** [TheSpeedX/TBomb#399]
**Describe the bug**
Tbomb isn't working at all! This is my first time using it. Everything worked according to Tutorial but got no SMS. Please Repair it and let me know.

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Terminal: Bash

**Smartphone (please complete the following information):**
 - Device: X616B
 - OS: Android 10
 - Terminal: Termux

**Additional context**
This isn't working at all!! Disstaisfied!

**Comment by 0n1cOn3** [comment]
RTFM again - It's obvious why its not working. This is because you are too lazy to read a simple README file! 

Such reports are tedious and almost a nuisance.

**Comment by nafisshagor** [comment]
@0n1cOn3 Hey! You better Watch it! Couldn't you could say it normally? I have read the Readme File but still it isn't working! People like you don't know how to talk properly with strangers!

**Comment by 0n1cOn3** [comment]
Im sorry, its not my issue when you don't understand whats written there. 
I'll repeat myself since 3 years but people acting as would they be dumb. 
If I hurt ya, excuse me. 

Here a snippet of the first 3 lines from the README.md file

_A free and open-source SMS/Call bombing application_

**NOTES:**

    Due to the overuse of script, a bunch of APIs have been taken offline. It is okay if you do not receive all the messages.
    
Theres no reason to be mad from my answer. I just can say what I see.

**Comment by opsboltz** [comment]
what do you mean its ok that your not getting messages? Thats the whole point sorry if the APIs are not on btw dont worry if the script doesnt work. :) WTF

**Comment by 0n1cOn3** [comment]
> what do you mean its ok that your not getting messages? Thats the whole point sorry if the APIs are not on btw dont worry if the script doesnt work. :) WTF

There are few reasons. I wrote that down in Telegram. 
You should be even able to read it without a user account:

https://t.me/TBombChat/40599
