### ISSUE TITLE
Traceback Error in opening tbomb although have downloaded colorama

### ISSUE THREAD

**Issue by LeViiAcKerMan01** [TheSpeedX/TBomb#403]
EVERYTIME I TRY TO OPEN TBOMB IT SHOWS TRACEBACK ERROR ,CAN ANYONE HELP ME FIX THIS ISSUE IT WILL BE A GREAT HELP!
![PXL_20230131_220332920](https://user-images.githubusercontent.com/124075086/215822330-dd5f2d42-ece2-4b5b-8fee-dc0a00819e04.jpg)
Please someone help me fix this issue if it could be     solved!

**Comment by 0n1cOn3** [comment]
> EVERYTIME I TRY TO OPEN TBOMB IT SHOWS TRACEBACK ERROR ,CAN ANYONE HELP ME FIX THIS ISSUE IT WILL BE A GREAT HELP!
> 
> ![PXL_20230131_220332920](https://user-images.githubusercontent.com/124075086/215822330-dd5f2d42-ece2-4b5b-8fee-dc0a00819e04.jpg)
> 
> Please someone help me fix this issue if it could be     solved!
> 
> 

Whats your current python version?
If it's greater than V3.10, you might have to downgrade to < V3.9.

TBomb has not been updated for python 3.10 and newer.

Edit: 12.02.2023
What also have to know is the OS your using

**Comment by LeViiAcKerMan01** [comment]
Has been fixed the way u said . I have installed python 3.9.6 and boom it works like charm.Thanks man for your help
