### ISSUE TITLE
TBOMB WILL BE OPENSOURCED

### ISSUE THREAD

**Issue by TheSpeedX** [TheSpeedX/TBomb#41]
Hello To ALL
Thanks To Guys Like @scpketer and @darkestentropy Who inspired Me To Make TBomb OpenSource
Thanks To issue https://github.com/darkestentropy/bombcrack/issues/6

I currently can no longer maintain TBomb By Adding APIs ...
I will  remove The Verification Code And Protect List Too ...

So its all on Contributors To Add New APIs To Keep The Project Alive...

Releasing Source Soon

**Comment by darkestentropy** [comment]
That's a right one decision.

**Comment by scpketer** [comment]
So glad I'm the part of this awesome event!
Sorry for all the pressure against you and TBomb - I just felt obligated to push you towards open source.

*'cause that's just what we do at GitHub*

**Comment by KnightSec-Official** [comment]
Its cool to keep a project hard encoded to ensure no modifications for misuse, but its not cool to ignore when someone asks for a decoded version...

**Comment by SwapnilSoni1999** [comment]
:heart:

**Comment by TheSpeedX** [comment]
@darkestentropy and @scpketer Made it Opensource
Will Be looking Forward To Your Contributions

Hope That People Dont Misuse it 😄

**Comment by sabari424** [comment]
Bro how to protect that sms
