### ISSUE TITLE
no such file or directory!!

### ISSUE THREAD

**Issue by HiuRiz** [TheSpeedX/TBomb#413]
![IMG_20230322_051155.jpg](https://user-images.githubusercontent.com/98296228/226766378-a495bffe-54c7-4ad1-8a59-6a4f0532a252.jpg)

i already installed python3 and termux is updated and downloaded from frdroid...CAN ANYBODY HELP ME OUT??why isnt this shit working?

**Comment by 0n1cOn3** [comment]
Skill issue. 
Folders are Case-Sensitive. 
Its not Tbomb, it is TBomb 😜
to execute after cd into TBomb:
./TBomb.sh
