### ISSUE TITLE
The Checking For Update Tooks lots of time even if the internet speed is good 

### ISSUE THREAD

**Issue by mrayushmehrotra** [TheSpeedX/TBomb#427]
**Describe the bug**
Stuck at Checking for update screen

**To Reproduce**
Normally open the TBomb.sh at the starting .

**Expected behavior**
should clear the checking for update screen if no updates were available 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Mint]
 - Terminal [e.g. bash, WSL, cygwin]
 - Python Version [e.g. 3.5, 3.8]

**Smartphone (please complete the following information):**
 - Terminal [e.g. iSH, Termux]
 - Python Version [e.g. 3.5, 3.8]

**Additional context**

**Comment by AdMediastic** [comment]
Having the same problem, in fact after some time, it throws an error called Network is unreachable. 
Downgrading Python is not a solution, I am on 3.9.2 

Please help!

**Comment by 0n1cOn3** [comment]
> Having the same problem, in fact after some time, it throws an error called Network is unreachable. Downgrading Python is not a solution, I am on 3.9.2
> 
> Please help!

Python3.9 is fine

You need to change in bomber.py, line 80 the following:

_requests.get("**https://motherfuckingwebsite.com**")_ 

--> Replace the URL here against one which does work for you!

**Comment by mrayushmehrotra** [comment]
i should close this issue because no one is working or want to fix this issue

**Comment by 0n1cOn3** [comment]
> i should close this issue because no one is working or want to fix this issue

I did sir. The preset of the URL does work for 99% of the people. 

And I have send a small guide how you can change this accordingly. 

Its not my fault if you didn't understood what I said. The fix is given with my previous answer.

To ask is for free if u know what I meant, u know :-)
