### ISSUE TITLE
Major issues with bomber.py code

### ISSUE THREAD

**Issue by darkestentropy** [TheSpeedX/TBomb#44]
This is something of a TODO list for contributors. I'll try to mark most critical issues I've seen so far at bomber.py

**By critical I mean the ones which affect code readability and/or violating Python code style conventions such as PEP8.**

*Click on item list to go to the line.*
### Partially resolved/less critical
* [Lines longer than 79 characters](https://github.com/TheSpeedX/TBomb/blob/c3ccddc988bb44862511db4afb0ff330392d1f91/bomber.py#L259) (partially fixed by `autopep8` prettifying in commit 4fdb588830a1f3eae4bbc03ad046e90236ab4836)
* [Two arrays used as a map](https://github.com/TheSpeedX/TBomb/blob/c3ccddc988bb44862511db4afb0ff330392d1f91/bomber.py#L17) (fixed in commit 4fdb588830a1f3eae4bbc03ad046e90236ab4836)
* [Colored text printed using `os.system` calls on `echo`](https://github.com/TheSpeedX/TBomb/blob/c3ccddc988bb44862511db4afb0ff330392d1f91/bomber.py#L27) (partially fixed by cutting off source lines in commit 4fdb588830a1f3eae4bbc03ad046e90236ab4836)
* [By-part phone number input](https://github.com/TheSpeedX/TBomb/blob/c3ccddc988bb44862511db4afb0ff330392d1f91/bomber.py#L267) (less critical)
* [Verification using own means instead of using package such as 'phonenumbers'](https://github.com/TheSpeedX/TBomb/blob/c3ccddc988bb44862511db4afb0ff330392d1f91/bomber.py#L275) (less critical)
* [Hardcoded text offsets made using `\t`](https://github.com/TheSpeedX/TBomb/blob/c3ccddc988bb44862511db4afb0ff330392d1f91/bomber.py#L66) (less critical, messed up CLI on small screens)

### Critical issues
* [Ambiguous and senseless variable names](https://github.com/TheSpeedX/TBomb/blob/c3ccddc988bb44862511db4afb0ff330392d1f91/bomber.py#L37)
* [For each implementation made in `if..elif` blocks](https://github.com/TheSpeedX/TBomb/blob/c3ccddc988bb44862511db4afb0ff330392d1f91/bomber.py#L70)
* [HTTP requests sent using `os.system` calls on `curl`](https://github.com/TheSpeedX/TBomb/blob/c3ccddc988bb44862511db4afb0ff330392d1f91/bomber.py#L83)
* [Redundant temporare files creation](https://github.com/TheSpeedX/TBomb/blob/c3ccddc988bb44862511db4afb0ff330392d1f91/bomber.py#L379)

To be continued.

**Comment by darkestentropy** [comment]
I strongly recommend **not to close** this issue until all critical issues are resolved.

**Comment by crinny** [comment]
Congratulations on finally making this public!

**Comment by darkestentropy** [comment]
@TheSpeedX updated the list, please review.

**Comment by TheSpeedX** [comment]
@darkestentropy Merged Your PR #45 
And using requests instead of curl will solve temporary file creation issue

**Comment by darkestentropy** [comment]
Sure, I've started working on converting `curl` calls to `requests` methods.

**Comment by crinny** [comment]
@darkestentropy I would highly suggest using `httpx` instead of `requests` as it has almost same API but it is a lot faster

**Comment by darkestentropy** [comment]
@crinny `requests` seem to have higher support and is more acknowledged by other developers, so that's why I planned to use it. I'll try it out though, thanks for suggestion.

**Comment by crinny** [comment]
Also you should probably use [black](https://github.com/psf/black) for formatting. It will keep clean appearance for your code

**Comment by darkestentropy** [comment]
`pycodestyle` seems to be more than enough, besides, original TBomb code is quite messed up, and I'm fixing its structure and formatting right now.

Sincerely, DarkestEntropy.

**Comment by TheSpeedX** [comment]
@darkestentropy Can You  Ping me With The Status ?
How Much You have covered in converting curl to requests

Sorry I wasn't Able To Participate in the dev But I will be back soon
So can You Ping Me With Your Status .?

**Comment by t0xic0der** [comment]
> @darkestentropy I would highly suggest using [httpx](https://github.com/encode/httpx) instead of `requests` as it has almost same API but it is a lot faster

Requests is a more elegant way of handling HTTP. It also has more support and the library is actively maintained. I do not see a reason in moving out of the library at this point of time.

**Comment by 0n1cOn3** [comment]
Whats the current Update? :)

**Comment by TheSpeedX** [comment]
Could be closed, all those critical issues are solved.
