### ISSUE TITLE
whare is protection list

### ISSUE THREAD

**Issue by prakasht1998** [TheSpeedX/TBomb#46]
how can i protect my number ?
i want to add my number in protection list.

**Comment by darkestentropy** [comment]
No longer available. See issue [#41](https://github.com/thespeedx/tbomb/issues/41)

Sincerely, DarkestEntropy.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by TheSpeedX** [comment]
@prakasht1998  TBomb no longer supports protection list. Consult your telephony subscription operator about what you can do to protect yourself from spam attacks.

Closing This issue As this issue now serves no purpose

**Comment by vklnnr** [comment]
Please open protection list ..some psycho is harassing me for 6 months...phone operator cant do anything

**Comment by 0n1cOn3** [comment]
@vklnnr See #46

**Comment by 0n1cOn3** [comment]
@vklnnr Your Phone is capable to block such trouble makers.

SMS & Phone. If you need help, please Join our Whatsapp Github Group.

@TheSpeedX Could you add the one of the Group link here?
