### ISSUE TITLE
API query.

### ISSUE THREAD

**Issue by mondoryink** [TheSpeedX/TBomb#469]
Is the API still working? As this repository seems to be active, the API might be still overused. Before I give time in it, it will be great to have some information about the API condition.

**Comment by 0n1cOn3** [comment]
Hi !

Most APIs are dead since two people forced the lead to fully open source TBomb with the APIs included. It took just 3-4 Weeks since then and the project was kinda dead. 

I'v also spoken with @TheSpeedX and he might stall the project and archiving it.

**Comment by 0n1cOn3** [comment]
But feel free, to fork, modify as u wish! :)
