### ISSUE TITLE
Protection list

### ISSUE THREAD

**Issue by Sreejakb** [TheSpeedX/TBomb#47]
I want to Protect my number

**Comment by adarsh1405** [comment]
Duplicate issue Refer To issue #41 
The Protect Number Feature is removed

**Comment by darkestentropy** [comment]
TBomb no longer supports protection list. Consult your telephony subscription operator about what you can do to protect yourself from spam attacks.

Sincerely, DarkestEntropy.

**Comment by TheSpeedX** [comment]
Closing This issue ...
Since it has been fully answered
