### ISSUE TITLE
Issue With Country code Invalid Or unsupported

### ISSUE THREAD

**Issue by Slayerma** [TheSpeedX/TBomb#489]
**Describe the bug**
- The bug is regarding the issue of not being able to run the python script because the country code entered is invalid or unsupported

**To Reproduce**
- It will ask which method to do weather it is sms, phone call or mail
- after selecting the method of bombing enter the Country code without adding '+' (91) and Number you want to bomb
- and after entering this it shows  Invalid Country Code or unsupported

**Expected behavior**
- It will bomb the number repeatedly for 100 tries and then stop

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Terminal: ~ZSH
 - Python Version:3.12

**Comment by 0n1cOn3** [comment]
Hi ! 😀 

Enter the number in international mode. Just be sure to to not add + infront of it as usual.

e.g:

Instead of:
+911234567890
it should be like that:
911234567890

**Comment by Slayerma** [comment]
Done
