### ISSUE TITLE
Multi-OS dependencies installation

### ISSUE THREAD

**Issue by scpketer** [TheSpeedX/TBomb#49]
Hello, @TheSpeedX.

As per your README, the setup script only supports Debian-based systems. You could use my [shelldepends script](https://github.com/scpketer/shelldepends) to generate a multi-os dependency installation script that is easy to use in your TBomb.sh.

Command line:
```bash
$ ./install-gen -e -p TBomb -v 1.6b -d python curl figlet toilet
```
`-e` disables access elevation in `install.sh`; `-p` defines project name; `-v` defines project version; `-d` defines dependency packages.

Installation script command line (this will work on most popular Linux distributions including Termux):
```bash
$ ./install.sh
```

Example preview:
![Termux sample preview](https://user-images.githubusercontent.com/31247845/68074612-5ac13f00-fdb6-11e9-8e99-0ff6b0d59bc0.png)

**Comment by TheSpeedX** [comment]
Looks Good @scpketer Thanks For The Idea
But I guess We Will Rather Wanna Make TBomb Dependency Free 
So We will only use python and a few PyPI Packages 
In That Way We Will Support Even More OS

Sorry I couldn't actively contribute To TBomb Now 
I Am trying to come back soon

**Comment by 0n1cOn3** [comment]
Perl and Gawk are also available in Termux. It makes installation easier with automatic preparations by Gawk. Personally, I would like to contribute

**Comment by scpketer** [comment]
> Perl and Gawk are also available in Termux. It makes installation easier with automatic preparations by Gawk. Personally, I would like to contribute

Yeah, gawk seem to be coming with core utilities provided by termux out-of-box.

**Comment by 0n1cOn3** [comment]
Also cause im a iOS Users,  theres a way to run TBomb aswell on a iPhone/iPod/iPad.

It needs just some script changes. (alpine linux x86 under the hood)

Also i made a pull request for a installation Guide for macOS aswell. 


I hope, SpeedX will think about it to migrate your Multi-OS Dep. Installer.

**Comment by 0n1cOn3** [comment]
Hi scpketer.

I have talked with SpeedX. Would you make a PR with your Multishell Script? He agreed, after i have explained him what your script does :)

Sincerly

0n1cOn3

**Comment by scpketer** [comment]
I'm working on a completely new code base which will no longer require any other external dependencies, so I don't think it would actually help.

**Comment by 0n1cOn3** [comment]
Ah, alright. That sounds good :-) 
    	
    	

    	Freundliche Grüsse
Stefan Kuny
    
  




On Tue, Jan 21, 2020 at 5:50 PM +0100, "Keterz" <notifications@github.com> wrote:












I'm working on a completely new code base which will no longer require any other external dependencies, so I don't think it would actually help.

**Comment by TheSpeedX** [comment]
Thanks @scpketer the bash script now includes a modified shelldepends script.

Reopen if issue persists
