### ISSUE TITLE
So glad I'm the part of this awesome event!

### ISSUE THREAD

**Issue by newkdr** [TheSpeedX/TBomb#495]
So glad I'm the part of this awesome event!
Sorry for all the pressure against you and TBomb - I just felt obligated to push you towards open source.

*'cause that's just what we do at GitHub*

_Originally posted by @ghost in https://github.com/TheSpeedX/TBomb/issues/41#issuecomment-544111527_

**Comment by 0n1cOn3** [comment]
> ```
>           So glad I'm the part of this awesome event!
> ```
> 
> Sorry for all the pressure against you and TBomb - I just felt obligated to push you towards open source.
> 
> _'cause that's just what we do at GitHub_
> 
> _Originally posted by @ghost in [#41 (comment)](https://github.com/TheSpeedX/TBomb/issues/41#issuecomment-544111527)_

??? Wdym
