### ISSUE TITLE
Python file encrypted?

### ISSUE THREAD

**Issue by CollyYT** [TheSpeedX/TBomb#5]
Can't edit code

**Comment by thistehneisen** [comment]
Yeah, what the heck?

**Comment by TheSpeedX** [comment]
Sorry to provide user safety and misuse of my script i have obfuscated the code 

Whether you like it or not i can't provide source code and risk user safety

Providing its source code will be like giving a weapon to everyone hands

**Comment by thistehneisen** [comment]
A halfly functioning watergun?

**Comment by TheSpeedX** [comment]
Can u say what was the issue

**Comment by kkthxbye-code** [comment]
> Can't edit code

Here you go: https://pastebin.com/GZPEc84L

It's terrible code though.

**Comment by TheSpeedX** [comment]
Sorry @kkthxbye-code 
Bro As you are a coder i think you know the possible misuse of your code can happen if you share it open
Hope that you understand me And Don't Share The Code ....

**Comment by thistehneisen** [comment]
@TheSpeedX what are you even talking about, the main purpose of the whole github is open-sourcing code. If you didn't want to open-source it, but to publish your gibberish, then just pay the price and afford private repositories. Nonetheless, the code itself is as I said previously "a halfly functioning watergun", there are far more advanced tools that could, quoting you "Providing its source code will be like giving a weapon to everyone hands". This is not even close to a weapon, more like some childish system that you want to keep some kind of power over.

**Comment by TheSpeedX** [comment]
@thistehneisen Bro i want people to use the code but not misuse in your case it might be a halfly functioning watergun but For indian users and many countries its a shinny sword...
It might not be woking well for your country..
If it had been a halfly functioning tool , It Could Have never reached heights and you wont be knowing about this That A Tool Like TBomb Even Exists...
As far as i know this tool provides bombing for Almost all countries with the most number of sms that any tool has ever given...
If You know any such advanced tools please drop a link Here

And there are many people posting binaries and obfuscated codes in github...
If you don't like it dont use it, but please dont demotivate us...
We are trying really hard to maintain it.

**Comment by 0n1cOn3** [comment]
@thistenheisen

There several other projects where only the binary is available. Without any Code.

The Bash script here is a part of the code. The python binary must be encrypted for the protection list where is build-in. 

We really work hard for TBomb and other projects. 

I hope, you can understand our decidment. 

Greeting

0n1cOn3

**Comment by dCHACKZz** [comment]
If the code  is encrypted how we   can check  this tool is safe

**Comment by TheSpeedX** [comment]
@dCHACKZz You can see other issues

There are people who decrypted And Verified....

If it had been a malware , It would have been taken down till now
Refer #20 To see the response

**Comment by darkestentropy** [comment]
> If the code is encrypted how we can check this tool is safe

@dCHACKZz You can ensure by using [my toolset](https://github.com/darkestentropy/bombcrack) that is capable of _cracking_ (i.e. decompressing & decoding) the script. Instructions are at README, be sure to check them.

**Comment by darkestentropy** [comment]
@TheSpeedX, @0n1cOn3 - as I've said in #22 and my conversation with TBomb author _aka TheSpeedX, GyanaTech_ (I'm not going to publish it, but you can ask them instead) - **I will do anything possible** to keep TBomb somewhat open, as long as license allows me to.

I'm not redistributing my project actively just to pay back for the TheSpeedX's kindness in responses.
