### ISSUE TITLE
Regarding updating the curl commands in python script 

### ISSUE THREAD

**Issue by deepakvamsi** [TheSpeedX/TBomb#51]
Hi @TheSpeedX  bomber.py file is outdated not working present can you update curl commands and cookies and only few is working maybe 13 or  show for sms and 2 for calls.

**Comment by TheSpeedX** [comment]
Yup @muskfan 
After I opensourced APIs started to die...
Currently I am dependent on user contribution for APIs

**Comment by muskfan** [comment]
I can able to help you with that,but even  it is going to be static ,other process is we have to automate  the dynamic parameters like cookie or id etc...to the code when ever user runs they have to get the code for fit repo.

**Comment by TheSpeedX** [comment]
Yeah @muskfan

I can do that using a cookie store
If it aint complex like going through multiple APIs for a single SMS then i
can do

And more over we can make a cookie store and store cookies till TBomb runs
such that the cookie thing wont interfere

And i see in most cases also cookie aint a issue only in some cases we need
the session id and all

**Comment by TheSpeedX** [comment]
This issue has been fixed. Reopen this if issue still persist.
