### ISSUE TITLE
I always get this error i start sms or call bomber.

### ISSUE THREAD

**Issue by k4rimhd** [TheSpeedX/TBomb#52]
When I launch the TBomb.sh it works fine but when I choose sms or call bomber it crashes and shows this message :

Traceback (most recent call last):                
File "bomber.py", line 3, in (module)

In termux

Please help me ASAP :'(

**Comment by TheSpeedX** [comment]
@k4rimhd  
Have u installed termcolor module??
Please install it by 
```python3 -m pip install termcolor```

**Comment by TheSpeedX** [comment]
Update @k4rimhd  To Fix it
