### ISSUE TITLE
Does not work on MacOS

### ISSUE THREAD

**Issue by Rizora** [TheSpeedX/TBomb#54]
Cannot complete steps :

brew install git
brew install python3

Script is rendered useless

**Comment by Rizora** [comment]
Infinite loop of "[!] Error: some dependencies are not installed
Type 'pip install -r requirements.txt' to install all required packages"

**Comment by Rizora** [comment]
pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: requests<3,>=2 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: urllib3<2,>=1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2)) (1.25.7)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /Library/Python/2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2.8)

**Comment by Rizora** [comment]
\e[1;31m
/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/TBomb.sh: line 27: figlet: command not found
\e[1;34m Created By \e[1;32m
/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/TBomb.sh: line 29: toilet: command not found
\e[4;34m This Bomber Was Created By SpeedX \e[0m
\e[1;34m For Any Queries Mail Me!!!\e[0m
\e[1;32m           Mail: ggspeedx29@gmail.com \e[0m
\e[4;32m   YouTube Page: https://www.youtube.com/c/GyanaTech \e[0m

when attempting to boot

**Comment by Rizora** [comment]
I give-up this will not work on Mac.

**Comment by 0n1cOn3** [comment]
> Cannot complete steps :
> 
> brew install git
> brew install python3
> 
> Script is rendered useless

Did you installed brew? 

Cause i can run it without any issue.

Btw, iv added the Guidline for macOS. Im responsive for macOS related Question.

**Comment by 0n1cOn3** [comment]
Just toilet is not available. But thats a "design" issue.

**Comment by TheSpeedX** [comment]
> Infinite loop of "[!] Error: some dependencies are not installed
> Type 'pip install -r requirements.txt' to install all required packages"

@Rizora Use Python3 
And pip3 for installing packages

You have not satisfied requirements to run the program .
This doesnt mean its useless

If you think so you can contribute and make better.


And as i guess this issue has been sorted out so closing it .. closes #54

If u got any issue related to this reopen it.
