### ISSUE TITLE
False Statement "International Not Supported"

### ISSUE THREAD

**Issue by Rizora** [TheSpeedX/TBomb#55]
Sorry But Call Bombing is Currently Supported Only For Indian Numbers!!!!

**Comment by TheSpeedX** [comment]
@Rizora Only SMS Bomb is supported for international not Call bomb 
We are trying out for call bomb

**Comment by 0n1cOn3** [comment]
###Can be closed###

**Comment by TheSpeedX** [comment]
Yah thanks for notifiying @0n1cOn3
