### ISSUE TITLE
Pip

### ISSUE THREAD

**Issue by Dissension** [TheSpeedX/TBomb#57]
When trying to start, it says "[!] Error: some dependencies are not installed                                    Type 'pip install -r requirements.txt' to install all required packages"

**Comment by Dissension** [comment]
Installed this. Its done but nothing changes.

**Comment by 0n1cOn3** [comment]
Reinstall TBomb and follow this Guide:

1.  $ rm -rf TBomb
2. $ git clone http://github.com/TheSpeedX/TBomb
3. $ cd TBomb
4. $ pip install -r requirements.txt
5. $ chmod +x TBomb.sh
6. $ ./TBomb.sh or bash TBomb.sh

**Comment by TheSpeedX** [comment]
@Dissension check your pip is referring to python2 or 3

Try python3 -m pip install requests 

If it dont work reopen it

Thanks @0n1cOn3  

Closes #57
