### ISSUE TITLE
Problem when sending more than 20 sms to one number.

### ISSUE THREAD

**Issue by Deathlive** [TheSpeedX/TBomb#6]
![photo_2019-07-18_13-57-54](https://user-images.githubusercontent.com/29791715/61448587-33a84400-a964-11e9-83ca-34c85599b2d0.jpg)

After sending 20 sms to one number. All sms are sent successfully. 

But when try to send another one sms, writes that `your country is not supported`.
I myself am from Armenia and am trying to send SMS to +374 (Armenian phone code).

What could be the problem and how to fix it ?
Or should the program work this way ?

**Comment by TheSpeedX** [comment]
Yes Due To Heavy Traffic On TBomb 
The APIs Got Banned ... So its showing not supported

We are still working hard on it

**Comment by Deathlive** [comment]
@TheSpeedX 
I see that you fixed the problem?
I think it is worth closing this issue.

**Comment by TheSpeedX** [comment]
Yes we Solved This issue

Thanks For reminding me to close this ;-)
