### ISSUE TITLE
TBomb new terminal UI demo

### ISSUE THREAD

**Issue by scpketer** [TheSpeedX/TBomb#60]
Hello, everyone!

I've been working on new TBomb terminal UI past few days, and here's what I've made so far:
![Peek 2020-01-29 15-18](https://user-images.githubusercontent.com/31247845/73352517-b5314500-42aa-11ea-8f24-b0a431b11ed4.gif)

I've reworked TBomb banner (made by the @darkestentropy) and reworked whole TBomb interface to be based on curses lib. Hope you will like it!

~~In a week or more, I'll create a PR with my reworked code.~~
It'll be done when it'll be done.

**Comment by TheSpeedX** [comment]
Any updates @scpketer

**Comment by scpketer** [comment]
I'm currently busy with migrating my stuff to gitlab, and I'm really lacking spare time. Still working on curl to requests recoding.

**Comment by mmvanheusden** [comment]
I like it!

**Comment by scpketer** [comment]
@TheSpeedX, take it from here. I have to leave at this point, so... use the sources I gave you. Give them a nice use.
