### ISSUE TITLE
pip is not working 

### ISSUE THREAD

**Issue by igotyou22** [TheSpeedX/TBomb#61]
I installed the pip and still ask for it. 

Type 'pip install -r requirements.txt' to install all required packages
bash: Type: command not found

[!] Error: some dependencies are not installed
Type 'pip install -r requirements.txt' to install all required packages

**Comment by 0n1cOn3** [comment]
pip3 or pip ?

**Comment by igotyou22** [comment]
I reinstallled and it worked.  Thanks for everthing. Maybe is Kail linux is the problem.  I am using parrot and it works here.

**Comment by igotyou22** [comment]
Thank you for everthing..

**Comment by igotyou22** [comment]
[!] Error: some dependencies are not installed
Type 'pip install -r requirements.txt' to install all required packages
┌─[XXXXXX]─[~/TBomb]
└──╼ $

**Comment by 0n1cOn3** [comment]
Did you run the command?

**Comment by Kabanos69** [comment]
[!] Error: some dependencies are not installed
Type 'pip install -r requirements.txt' to install all required packages

Requirement already satisfied: requests<3,>=2 in /home/kabanos/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: urllib3<2,>=1 in /home/kabanos/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /home/kabanos/.local/lib/python2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/kabanos/.local/lib/python2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/kabanos/.local/lib/python2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2019.11.28)

same problem and i have python 3 as requested for the script to run
python -V
Python 3.7.6

**Comment by 0n1cOn3** [comment]
python3 -m pip install -r requirements.txt

**Comment by 0n1cOn3** [comment]
aswell for python2
for sure.

**Comment by Kabanos69** [comment]
python3 pip install -r requirements.txt
python3: can't open file 'pip': [Errno 2] No such file or directory

python3 pip3 install -r requirements.txt
python3: can't open file 'pip3': [Errno 2] No such file or directory

pip3 install -r requirements.txt
Requirement already satisfied: requests<3,>=2 in /home/kabanos/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: urllib3<2,>=1 in /home/kabanos/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2.8)

python2 pip install -r requirements.txt
python2: can't open file 'pip': [Errno 2] No such file or directory

python2 pip2 install -r requirements.txt
python2: can't open file 'pip2': [Errno 2] No such file or directory

 pip2 install -r requirements.txt
Requirement already satisfied: requests<3,>=2 in /home/kabanos/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: urllib3<2,>=1 in /home/kabanos/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /home/kabanos/.local/lib/python2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/kabanos/.local/lib/python2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/kabanos/.local/lib/python2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2019.11.28)

im trying to run the script on kali subsystem again same problem

**Comment by TheSpeedX** [comment]
> 
> 
> python3 pip install -r requirements.txt
> python3: can't open file 'pip': [Errno 2] No such file or directory
> 
> python3 pip3 install -r requirements.txt
> python3: can't open file 'pip3': [Errno 2] No such file or directory
> 
> pip3 install -r requirements.txt
> Requirement already satisfied: requests<3,>=2 in /home/kabanos/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.22.0)
> Requirement already satisfied: urllib3<2,>=1 in /home/kabanos/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.25.8)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (3.0.4)
> Requirement already satisfied: certifi>=2017.4.17 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2019.11.28)
> Requirement already satisfied: idna<2.9,>=2.5 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2.8)
> 
> python2 pip install -r requirements.txt
> python2: can't open file 'pip': [Errno 2] No such file or directory
> 
> python2 pip2 install -r requirements.txt
> python2: can't open file 'pip2': [Errno 2] No such file or directory
> 
> pip2 install -r requirements.txt
> Requirement already satisfied: requests<3,>=2 in /home/kabanos/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2.22.0)
> Requirement already satisfied: urllib3<2,>=1 in /home/kabanos/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (1.25.8)
> Requirement already satisfied: idna<2.9,>=2.5 in /home/kabanos/.local/lib/python2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2.8)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/kabanos/.local/lib/python2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (3.0.4)
> Requirement already satisfied: certifi>=2017.4.17 in /home/kabanos/.local/lib/python2.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2019.11.28)
> 
> im trying to run the script on kali subsystem

@Kabanos69 @igotyou22  
As @0n1cOn3  Already said Try
```python3 -m pip install -r requirements.txt```  or ```python3 -m pip install -r requirements.txt --user``` (if you are not sudo user)
This will do....
 @Kabanos69 You are4 missing **-m**

**Comment by Kabanos69** [comment]
[!] Error: some dependencies are not installed
Type 'pip install -r requirements.txt' to install all required packages

python3 -m pip install -r requirements.txt --user
Requirement already satisfied: requests<3,>=2 in /home/kabanos/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: urllib3<2,>=1 in /home/kabanos/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2.8)

python3 -m pip install -r requirements.txt
Requirement already satisfied: requests<3,>=2 in /home/kabanos/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: urllib3<2,>=1 in /home/kabanos/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/kabanos/.local/lib/python3.7/site-packages (from requests<3,>=2->-r requirements.txt (line 1)) (3.0.4)

Again same problem but i'm not interested in solving it any more i just run the script of my phone with Termux and it works great

**Comment by shubhamgawri** [comment]
After trying all above method it didnt work 
But then i tried...
`sudo python3 -m pip install -r requirements.txt`
voila !!! it worked!!!!!!!!

**Comment by igotyou22** [comment]
this what gives me. WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.Collecting requests<3,>=2 (from -r requirements.txt (line 1))WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/Could not fetch URL https://pypi.org/simple/requests/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/requests/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skippingERROR: Could not find a version that satisfies the requirement requests<3,>=2 (from -r requirements.txt (line 1)) (from versions: none)ERROR: No matching distribution found for requests<3,>=2 (from -r requirements.txt (line 1))WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping Also, if  I use pycharm it does work. Thanks  19.02.2020, 22:44, "shubhamgawri" <notifications@github.com>:After trying all above method it didnt workBut then i tried...sudo python3 -m pip install -r requirements.txtvoila !!! it worked!!!!!!!!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by 0n1cOn3** [comment]
Reinstall Python and Pip and try again.
