### ISSUE TITLE
They Want Login

### ISSUE THREAD

**Issue by Rahul-Singh-Ap** [TheSpeedX/TBomb#64]
![photo_2020-02-14_17-26-30](https://user-images.githubusercontent.com/53531385/74530093-3fd29f00-4f4f-11ea-9502-6bb2f6ebd51d.jpg)

they want username and password i try with my account but they say authentication failed what i do now

**Comment by TheSpeedX** [comment]
@Rahul-Singh-Ap 
Bro Make sure to type correct url , You are missing last letter !!

This issue is invalid Closing it
