### ISSUE TITLE
Please indicate this package only available for Indian Number.

### ISSUE THREAD

**Issue by Jensenkho** [TheSpeedX/TBomb#66]
Option 1 : ValueError: invalid literal for int() with base 10: 'halo' 
Option 2 : Sorry but call bombing is currently supported only for Indian number.

**Comment by TheSpeedX** [comment]
@Jensenkho 
Option 1:   The Code asks number of messages not what message to send
Custom messages aren't available
Option 2:  The Call Bombing is supported only for indian numbers due to lack of apis 
but sms bombing is world wide

**Comment by Jensenkho** [comment]
> @Jensenkho
> Option 1: The Code asks number of messages not what message to send
> Custom messages aren't available
> Option 2: The Call Bombing is supported only for indian numbers due to lack of apis
> but sms bombing is world wide

**Comment by Jensenkho** [comment]
@TheSpeedX 
Option 2: understood.
Option 1: I try again on this option with correct input, however "Sorry Your Country is not support, please send an email to let us know."
