### ISSUE TITLE
Can it be used on windows

### ISSUE THREAD

**Issue by qianniandazongzi** [TheSpeedX/TBomb#67]
Can I use it on Windows ?, how to use it on iOS, do I need to jailbreak my iPhone?

**Comment by TheSpeedX** [comment]
yup on the next update ,
you can use on windows or ios no need to jailbreak you can simply use iSH app

**Comment by 0n1cOn3** [comment]
On Windows, if you can run WSL you should able to install all dependecys which TBomb requiered.

on iOS, some non-essential Packages are not available in iSH App. But it is working so far.

**Comment by dipsagar11** [comment]
Plz add np+977 also

**Comment by TheSpeedX** [comment]
Now it can be used on windows as well most probably except the call one will port that soon

**Comment by bukyapavankumar** [comment]
We can run it in terminal on android right

**Comment by Bhatyawar** [comment]
Sir i wanna packages for sending spam sms through termux on android

**Comment by 0n1cOn3** [comment]
> We can run it in terminal on android right

Yes, with Termux App

**Comment by 0n1cOn3** [comment]
> Sir i wanna packages for sending spam sms through termux on android

TBomb is made for Termux, Linux, MacOS and Windows

**Comment by 0n1cOn3** [comment]
> Can I use it on Windows ?, how to use it on iOS, do I need to jailbreak my iPhone?

Feel free to contact me for iOS and iSH.

**Comment by delwindro** [comment]
You can stop for spam my Gmail?

Pada tanggal Sab, 16 Mei 2020 16.12, SpeedX <notifications@github.com>
menulis:

**Comment by rao-zameer** [comment]
How to use it on ish/ios
