### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by jeremie1112** [TheSpeedX/TBomb#70]
Getting this error when doing this option "Press 1 To  Start SMS Bomber"
```
  File "bomber.py", line 311
    headers = {
              ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by TheSpeedX** [comment]
i got it fixed in latest commit just do a git pull and update to latest version.
This will fix it @jeremie1112
