### ISSUE TITLE
SMS Recieve

### ISSUE THREAD

**Issue by Ahamedgksy** [TheSpeedX/TBomb#73]
Hello there 
I am from Srilanka and I used tbomb but I received only one message I configured for 10 message and 2, 10 second delay
Please give me a solution and I am using updated version 
Thank you

**Comment by TheSpeedX** [comment]
Well APIs are getting outdated. I will add some new soon .
It a duplicate issue so closing

**Comment by Ahamedgksy** [comment]
Okay thank you then we have to wait more

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
