### ISSUE TITLE
sms limit and threads

### ISSUE THREAD

**Issue by PrixHacks** [TheSpeedX/TBomb#8]
please increase the maximum limit (400 is too low) and increase maximum threads level. PLEASE

**Comment by TheSpeedX** [comment]
Bro To Limit Misuse Of script i need to limit the bomber to 400

But you can Use the Bomber Again To Spam Same Number

And Maximum Thread Can be as your wish but 10-20 os recommended for maximum performance

**Comment by lalatianhp234** [comment]
What does therad means

**Comment by 0n1cOn3** [comment]
It has been explained here 🙂

**Comment by Kshitij230** [comment]
where???

**Comment by 0n1cOn3** [comment]
No, the API has been already abused due that and we won't increase the limits.

**Comment by Kshitij230** [comment]
Can anyone tell me what are threads?
And what threads should we use with 15 sms bombings?

**Comment by 0n1cOn3** [comment]
Well, increasing the limit will cause the APIs that TBomb uses to fail faster. Please understand this. It is not forbidden to run multiple instances at the same time.
