### ISSUE TITLE
Script slow in Kali/Parrot OS

### ISSUE THREAD

**Issue by basimci** [TheSpeedX/TBomb#81]
Script runs fast in Windows 10 and Termux but is too slow in Kali/Parrot OS.
it get stuck after choosing the sms or call option from menu and then it just shows the logo.

**Comment by 0n1cOn3** [comment]
Thank you for your report. We gonna check that issue and let you know when we have further information.

**Comment by TheSpeedX** [comment]
@basimci We have tested it in different linux distros 
Check if your internet is fine and you have all dependencies installed

Feel free to reopen if it does not solve
