### ISSUE TITLE
Script working very slow on other countries except india

### ISSUE THREAD

**Issue by dx4iot** [TheSpeedX/TBomb#82]

**Comment by TheSpeedX** [comment]
@dx4iot  Well i updated a few indian apis 
Still look for contributions for international ones

**Comment by 0n1cOn3** [comment]
Feel free to contribute if you get any international API’s. :-)

**Comment by t0xic0der** [comment]
As it is clearly stated in the third point [here](https://github.com/TheSpeedX/TBomb#features), the international APIs are not actively worked on. @dx4iot You can provide international APIs if you wish as @0n1cOn3 specified though. :slightly_smiling_face:
