### ISSUE TITLE
Total Number of SMS received is less than the ones requested and successful

### ISSUE THREAD

**Issue by Qwerty246246** [TheSpeedX/TBomb#93]
When I send 10 sms and successful req is 10 , the actual received sms is 6 . When I send 5 , received sms on phone is 1 . When I send 12 , received sms is 7 .

**Comment by 0n1cOn3** [comment]
Several international API’s are expired.

**Comment by TheSpeedX** [comment]
well there is no 100% delivery ratio as it isnt paid apis
